[package]
name = "aoc2019"
version = "0.1.0"
authors = ["blueblank <blueblank@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"
pathfinding = "2.0.0"
